### ISSUE TITLE
pipeline does not work on conda eniroment

### ISSUE THREAD

**Issue by tomy7912348** [AIObjectives/talk-to-the-city-reports#16]
Trying to run the pipeline on conda enviroment with Ubuntu22.04 in python = 3.11.5. When running pipeline with example file. pipeline was interrupted with below messege.

```

So, here is what I am planning to run:
{'step': 'extraction', 'run': False, 'reason': 'nothing changed'}
{'step': 'embedding', 'run': False, 'reason': 'nothing changed'}
{'step': 'clustering', 'run': False, 'reason': 'nothing changed'}
{'step': 'labelling', 'run': False, 'reason': 'nothing changed'}
{'step': 'takeaways', 'run': False, 'reason': 'nothing changed'}
{'step': 'overview', 'run': False, 'reason': 'nothing changed'}
{'step': 'translation', 'run': False, 'reason': 'nothing changed'}
{'step': 'aggregation', 'run': False, 'reason': 'nothing changed'}
{'step': 'visualization', 'run': True, 'reason': 'previous data not found'}
Looks good? Press enter to continue or Ctrl+C to abort.

Skipping 'extraction'
Skipping 'embedding'
Skipping 'clustering'
Skipping 'labelling'
Skipping 'takeaways'
Skipping 'overview'
Skipping 'translation'
Skipping 'aggregation'
Running step: visualization

> next-app@0.1.0 build
> next build

Errors:
/home/elilin/tttc/next-app/node_modules/next/dist/lib/picocolors.js:130
const { env, stdout } = ((_globalThis = globalThis) == null ? void 0 : _globalThis.process) ?? {};
                                                                                             ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at Module.mod.require (/home/elilin/tttc/next-app/node_modules/next/dist/server/require-hook.js:64:28)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/elilin/tttc/next-app/node_modules/next/dist/build/output/log.js:55:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

Pipeline completed.
```

**Comment by tomy7912348** [comment]
so I deactivate conda enviroment and tried agian on venv in python3.11. But problem still persist, so it doesn't looks like that the problem is with conda.

```
So, here is what I am planning to run:
{'step': 'extraction', 'run': False, 'reason': 'nothing changed'}
{'step': 'embedding', 'run': False, 'reason': 'nothing changed'}
{'step': 'clustering', 'run': False, 'reason': 'nothing changed'}
{'step': 'labelling', 'run': False, 'reason': 'nothing changed'}
{'step': 'takeaways', 'run': False, 'reason': 'nothing changed'}
{'step': 'overview', 'run': False, 'reason': 'nothing changed'}
{'step': 'translation', 'run': False, 'reason': 'nothing changed'}
{'step': 'aggregation', 'run': False, 'reason': 'nothing changed'}
{'step': 'visualization', 'run': True, 'reason': 'previous data not found'}
Looks good? Press enter to continue or Ctrl+C to abort.

Skipping 'extraction'
Skipping 'embedding'
Skipping 'clustering'
Skipping 'labelling'
Skipping 'takeaways'
Skipping 'overview'
Skipping 'translation'
Skipping 'aggregation'
Running step: visualization

> next-app@0.1.0 build
> next build

Errors:
/home/elilin/tttc/next-app/node_modules/next/dist/lib/picocolors.js:130
const { env, stdout } = ((_globalThis = globalThis) == null ? void 0 : _globalThis.process) ?? {};
                                                                                             ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at Module.mod.require (/home/elilin/tttc/next-app/node_modules/next/dist/server/require-hook.js:64:28)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/elilin/tttc/next-app/node_modules/next/dist/build/output/log.js:55:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

Pipeline completed.

```

**Comment by Onurbon** [comment]
Hi Eli, this looks more like a Javascript problem than a Python because the error is apparently occurring during the `visualization` step which spawns a subprocess calling `next build`. 

Can you try to delete your `node_modules` folder, then make sure you have a recent version of node (say v18+), and reinstall the javascript dependencies with`npm install` from `next-app`?

**Comment by tomy7912348** [comment]
fixed after updating node.js to v21. Thanks!
