### ISSUE TITLE
Error message with error 401 & can’t read prop of undefined

### ISSUE THREAD

**Issue by theboldzoey** [AIObjectives/talk-to-the-city-reports#180]
**Describe the bug**

**To Reproduce**
1. Click on project '<project_name>'
2. Click on cluster '<cluster_name>' (if applicable)
3. Scroll down to '<relevant_section>'
4. *bug* 
`/api/users/info/email?uid=s5GEWmqDNjSE353plcOYO0UfWVX2:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()
/api/users/info/email?uid=s5GEWmqDNjSE353plcOYO0UfWVX2:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()
/api/users/info/email?uid=s5GEWmqDNjSE353plcOYO0UfWVX2:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()
/api/users/info/email?uid=s5GEWmqDNjSE353plcOYO0UfWVX2:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()
templates.cc721717.js:669 TypeError: o[R].trim is not a function
    at AwI.isValidRow (templates.cc721717.js:387:5497)
    at AwI.filterValidRows (templates.cc721717.js:387:5422)
    at AwI.compute (templates.cc721717.js:387:4840)
    at async templates.cc721717.js:669:5608
    at async Promise.all (wishing-well/index 1)
    at async RdA.processNodes (templates.cc721717.js:669:6132)
    at async I (Pipeline.8234ce58.js:382:23508)
(anonymous) @ templates.cc721717.js:669
templates.cc721717.js:669 TypeError: Cannot read properties of undefined (reading '')
    at swI.compute (templates.cc721717.js:578:555)
    at templates.cc721717.js:669:5616
    at templates.cc721717.js:669:6126
    at Array.map (<anonymous>)
    at RdA.processNodes (templates.cc721717.js:669:5243)
    at async I (Pipeline.8234ce58.js:382:23508)
(anonymous) @ templates.cc721717.js:669
Report.951e0033.js:5811 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'merge')
    at Av.e.$$.update (Report.951e0033.js:5811:27702)
    at pt (scheduler.5f44e3c0.js:1:10124)
    at mt (scheduler.5f44e3c0.js:1:9857) `

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**Screenshots**

**Additional context**

**Comment by lightningorb** [comment]
Can you see which node produces this error? I think all of the error message pasted here are noise. The one that matters is "OpenAI request timed out".

Calls to OpenAI are resilient, by waiting and retrying several times. So these bugs should be transient. Please note it's really important to fill all the fields when filing bugs, with a reference to the problematic report. Also there should be a red visible error on the node that triggered the issue. Ideally that should be filed too.
